from django.urls import path
from .views import (
    ParentDocumentListView,
    parent_documents_by_category,
    parent_document_file,
    franchise_document_file,
    franchise_documents_all,
    franchise_documents_by_category,
    admin_franchise_documents_summary,
    FranchiseParentDocumentListCreateView,
    FranchiseParentDocumentDetailView,
    AdminParentDocumentListCreateView,
    AdminParentDocumentDetailView,
    FranchiseCentreDocumentListCreateView,
    FranchiseCentreDocumentDetailView,
    FranchiseIndentRequestListCreateView,
    AdminIndentRequestListView,
    AdminIndentRequestUpdateView,
    AdminFranchiseDocumentListCreateView,
    AdminFranchiseDocumentDetailView,
    admin_sync_pc_documents,
)

urlpatterns = [
    path('parent/documents/', ParentDocumentListView.as_view(), name='parent-documents'),
    path('parent/documents/<int:pk>/file/', parent_document_file, name='parent-document-file'),
    path('parent/documents/category/<str:category>/', parent_documents_by_category, name='parent-documents-category'),
    path('franchise/documents/', franchise_documents_all, name='franchise-documents-all'),
    path('franchise/documents/<int:pk>/file/', franchise_document_file, name='franchise-document-file'),
    path('franchise/documents/category/<str:category>/', franchise_documents_by_category, name='franchise-documents-category'),
    path('franchise/parent-documents/', FranchiseParentDocumentListCreateView.as_view(), name='franchise-parent-documents'),
    path('franchise/parent-documents/<int:pk>/', FranchiseParentDocumentDetailView.as_view(), name='franchise-parent-document-detail'),
    path('admin/parent-documents/', AdminParentDocumentListCreateView.as_view(), name='admin-parent-documents'),
    path('admin/parent-documents/<int:pk>/', AdminParentDocumentDetailView.as_view(), name='admin-parent-document-detail'),
    path('franchise/centre-documents/', FranchiseCentreDocumentListCreateView.as_view(), name='franchise-centre-documents'),
    path('franchise/centre-documents/<int:pk>/', FranchiseCentreDocumentDetailView.as_view(), name='franchise-centre-document-detail'),
    path('franchise/indents/', FranchiseIndentRequestListCreateView.as_view(), name='franchise-indent-requests'),
    path('admin/indents/', AdminIndentRequestListView.as_view(), name='admin-indent-requests'),
    path('admin/indents/<int:pk>/', AdminIndentRequestUpdateView.as_view(), name='admin-indent-request-update'),
    path('admin/franchise-documents/summary/', admin_franchise_documents_summary, name='admin-franchise-documents-summary'),
    path('admin/franchise-documents/sync-pc/', admin_sync_pc_documents, name='admin-franchise-documents-sync-pc'),
    path('admin/franchise-documents/', AdminFranchiseDocumentListCreateView.as_view(), name='admin-franchise-documents'),
    path('admin/franchise-documents/<int:pk>/', AdminFranchiseDocumentDetailView.as_view(), name='admin-franchise-document-detail'),
]

