# Generated by Django 5.0.14 on 2026-01-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='career',
            name='type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
    ]
