# Generated by Django 6.0 on 2026-04-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0011_franchise_latitude_franchise_longitude'),
        ('students', '0003_portal_and_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_key', models.CharField(max_length=120)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notifications', to='franchises.parentprofile')),
            ],
            options={
                'ordering': ['-read_at'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'notification_key'), name='uniq_parent_notification_key')],
            },
        ),
    ]
