# Generated by Django 6.0 on 2026-04-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_parentnotificationread'),
    ]

    operations = [
        migrations.AddField(
            model_name='feerecord',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='fee_structure_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='id_card_no',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
