# Generated by Django 6.0 on 2026-04-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0012_alter_parentprofile_notifications_muted_and_more'),
        ('students', '0006_transportroute_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportroute',
            name='driver_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_routes', to='franchises.driverprofile'),
        ),
    ]
