# Generated by Django 6.0 on 2026-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_transportroute_driver_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporttriplocation',
            name='latitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='transporttriplocation',
            name='longitude',
            field=models.DecimalField(decimal_places=16, max_digits=22),
        ),
    ]
