# Generated by Django 6.0 on 2026-04-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_transporttriplocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttrip',
            name='is_gps_active',
            field=models.BooleanField(default=True),
        ),
    ]
