# Generated by Django 6.0 on 2026-04-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_transporttrip_is_gps_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='blood_group',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
