# Generated by Django 6.0 on 2026-04-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentprofile_blood_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_name',
            field=models.CharField(help_text='e.g., KG-2', max_length=50),
        ),
    ]
