# Generated by Django 6.0 on 2026-05-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentprofile_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportroute',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
