# Generated by Django 6.0 on 2026-05-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_transportroute_destination_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttransportassignment',
            name='drop_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='drop_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='studenttransportassignment',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
