# Generated by Django 6.0 on 2026-05-14 09:30
#
# Uses IF NOT EXISTS so migrate succeeds when some legacy columns were already
# added manually or from a partial import (e.g. batch_num).

from django.db import migrations, models


ADD_LEGACY_COLUMNS_SQL = """
DO $legacy$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'academic_year'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN academic_year varchar(100) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'batch_num'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN batch_num varchar(50) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'centre_name'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN centre_name varchar(255) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'city'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN city varchar(255) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'email'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN email varchar(254) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'legacy_password'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN legacy_password varchar(255) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'parent_name'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN parent_name varchar(255) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'state'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN state varchar(255) NULL;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema() AND table_name = 'students_studentprofile' AND column_name = 'student_code'
  ) THEN
    ALTER TABLE students_studentprofile ADD COLUMN student_code varchar(255) NULL;
  END IF;
END $legacy$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_homeworkassignment_attachment"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="studentprofile",
                    name="academic_year",
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="batch_num",
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="centre_name",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="city",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="email",
                    field=models.EmailField(blank=True, max_length=254, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="legacy_password",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="parent_name",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="state",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name="studentprofile",
                    name="student_code",
                    field=models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(ADD_LEGACY_COLUMNS_SQL, migrations.RunSQL.noop),
            ],
        ),
    ]
