# Generated by Django 6.0 on 2026-05-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_legacy_sql_column_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_num',
            field=models.CharField(blank=True, db_column='batch_num', max_length=50, null=True),
        ),
    ]
