# Generated by Django 6.0 on 2026-06-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0020_driverprofile_vehicle_documents'),
        ('students', '0019_studentprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_serial', models.PositiveIntegerField(default=0)),
                ('fee_type', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('mode_of_payment', models.CharField(default='UPI QR', max_length=64)),
                ('transaction_ref', models.CharField(blank=True, db_index=True, max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_payments', to='students.feerecord')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='franchises.parentprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Parent fee payment',
                'verbose_name_plural': 'Parent fee payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
