# Generated by Django 6.0 on 2026-06-19 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_centre_attendance_closed_day'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='franchisenotification',
            new_name='students_fr_franchi_4b1e00_idx',
            old_name='students_fr_franchi_6e2a0d_idx',
        ),
        migrations.RenameIndex(
            model_name='franchisenotification',
            new_name='students_fr_franchi_f3b4cf_idx',
            old_name='students_fr_franchi_8c4f1a_idx',
        ),
    ]
