# Generated by Django 6.0 on 2026-07-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0029_centre_attendance_closed_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportroute',
            name='driver_token',
        ),
    ]
