# Generated by Django 6.0 on 2026-07-10 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_remove_transportroute_driver_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportroute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='destination_latitude',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='destination_longitude',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='transportroute',
            name='tracking_note',
        ),
    ]
