# Generated by Django 6.0 on 2026-07-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0021_driveractivitylog'),
        ('students', '0031_remove_transportroute_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, help_text='Must match StudentProfile.class_name. Empty = all classes at centre.', max_length=120)),
                ('activity_date', models.DateField()),
                ('description', models.TextField(help_text='Short description/brief of the activities conducted.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Daily activity',
                'verbose_name_plural': 'Daily activities',
                'ordering': ['-activity_date', 'class_name'],
                'constraints': [models.UniqueConstraint(fields=('franchise', 'class_name', 'activity_date'), name='uniq_franchise_class_activity_date')],
            },
        ),
    ]
