# Generated by Django 6.0 on 2026-07-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0032_dailyactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_image', models.FileField(blank=True, null=True, upload_to='students/homework_submissions/')),
                ('is_completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.homeworkassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Homework submission',
                'verbose_name_plural': 'Homework submissions',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'homework')},
            },
        ),
    ]
