# Generated by Django 6.0 on 2026-07-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0033_homeworksubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='students/homework_submissions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='students.homeworksubmission')),
            ],
            options={
                'verbose_name': 'Homework submission image',
                'verbose_name_plural': 'Homework submission images',
                'ordering': ['created_at'],
            },
        ),
    ]
