# Generated by Django 5.0.14 on 2026-01-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Classroom', 'Classroom'), ('Activities', 'Activities'), ('Campus', 'Campus')], default='Events', max_length=20),
        ),
    ]
