# Generated by Django 5.0.14 on 2026-01-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_mediaitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Classroom', 'Classroom'), ('Activities', 'Activities'), ('Campus', 'Campus'), ('Banner', 'Banner')], default='Events', max_length=20),
        ),
    ]
