# Generated by Django 6.0.1 on 2026-01-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_mediaitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
