# Generated by Django 6.0 on 2026-05-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_gallerysection_mediaitem_embed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
