# Generated by Django 5.0.14 on 2026-01-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='link',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
