# Generated by Django 6.0 on 2026-04-20 04:24

import common.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_home_page_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='data',
            field=common.models.HomePageJSONField(default=dict),
        ),
    ]
