# Generated by Django 6.0 on 2026-05-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_home_page_json_field_subclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="e.g. 'admission-brochure', 'franchise-brochure', 'virtual-tour'", unique=True)),
                ('file', models.FileField(blank=True, help_text='Upload the file (PDF, etc.)', null=True, upload_to='assets/')),
                ('link', models.URLField(blank=True, help_text='Or provide a link (e.g. YouTube virtual tour)', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing asset',
                'verbose_name_plural': 'Marketing assets',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Page identifier (e.g. 'admission', 'franchise-opportunity')", unique=True)),
                ('data', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page content',
                'verbose_name_plural': 'Page contents',
            },
        ),
    ]
