# Generated by Django 6.0 on 2026-05-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_home_testimonial_category'),
        ('common', '0009_state_city'),
    ]

    operations = [
    ]
