# Generated by Django 6.0 on 2026-04-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_add_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('APPROVER', 'Approver'), ('FRANCHISE', 'Franchise'), ('PARENT', 'Parent'), ('DRIVER', 'Driver')], max_length=20),
        ),
    ]
