# Generated by Django 6.0 on 2026-07-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_parentregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('APPROVER', 'Approver'), ('CRM', 'CRM'), ('FRANCHISE', 'Franchise'), ('PARENT', 'Parent'), ('DRIVER', 'Driver')], max_length=20),
        ),
    ]
