# Generated by Django 6.0 on 2026-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_zone',
            field=models.CharField(blank=True, choices=[('EAST', 'East'), ('WEST', 'West'), ('NORTH', 'North'), ('SOUTH', 'South')], default='', help_text="CRM only: blank = all India; otherwise only that zone's states/cities/centres.", max_length=10),
        ),
    ]
