# Generated by Django 6.0 on 2026-07-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_crm_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_region',
            field=models.CharField(blank=True, default='', help_text='CRM only: blank = full zone/national; otherwise a region code (e.g. NORTH_R1).', max_length=20),
        ),
    ]
