# Generated by Django 6.0 on 2026-07-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_crm_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_cities',
            field=models.CharField(blank=True, default='', help_text='CRM only: comma-separated cities/districts (e.g. Ernakulam,Kollam).', max_length=800),
        ),
        migrations.AddField(
            model_name='user',
            name='crm_states',
            field=models.CharField(blank=True, default='', help_text='CRM only: comma-separated state codes (e.g. AP,TG,KL). Overrides zone/region when set.', max_length=120),
        ),
    ]
