# Generated by Django 6.0 on 2026-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_crm_states_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_notify_leads',
            field=models.BooleanField(default=False, help_text='CRM only: receive new-lead email notifications for this territory.'),
        ),
    ]
