# Generated by Django 6.0 on 2026-10-08 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_correct_kerala_crm_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crm_handles_admission',
            field=models.BooleanField(default=False, help_text='CRM only: can be assigned Admission leads (Users page).'),
        ),
        migrations.AddField(
            model_name='user',
            name='crm_handles_franchise',
            field=models.BooleanField(default=False, help_text='CRM only: can be assigned Franchise leads (Users page).'),
        ),
        migrations.AddField(
            model_name='user',
            name='crm_reports_to',
            field=models.ForeignKey(blank=True, help_text='CRM only: Zonal / Regional Manager this user reports to (Users page).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('APPROVER', 'Approver'), ('CRM', 'CRM'), ('FRANCHISE', 'Franchise'), ('PARENT', 'Parent'), ('DRIVER', 'Driver'), ('TEACHER', 'Teacher')], max_length=20),
        ),
    ]
