# Generated by Django 5.2.9 on 2026-01-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
