# Generated by Django 6.0 on 2026-05-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_alter_enquiry_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enquiry',
            table='enquiry',
        ),
    ]
