# Generated by Django 6.0 on 2026-07-03 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_crmlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CrmLeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='enquiries.crmlead')),
            ],
            options={
                'db_table': 'crm_lead_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
