# Generated by Django 6.0 on 2026-07-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_crm_lead_notes_and_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('converted', 'Converted'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('in-progress', 'In Progress'), ('closed', 'Closed')], default='new', max_length=30),
        ),
    ]
