# Generated by Django 6.0 on 2026-07-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_enquiry_status_crm_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseenquiry',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
