# Generated by Django 6.0 on 2026-07-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0012_franchiseenquiry_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedLeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(db_index=True, max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'unified_lead_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
