# Generated by Django 6.0 on 2026-07-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0013_unifiedleadnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseenquiry',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='franchiseenquiry',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kidsenquiry',
            name='meeting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kidsenquiry',
            name='next_follow_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
