# Generated by Django 6.0 on 2026-07-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0014_enquiry_meeting_date_enquiry_next_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('converted', 'Converted'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested'), ('untouched', 'Untouched'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU Signed'), ('converted_agreement_signed', 'Converted – Agreement Signed'), ('join_later', 'Join Later'), ('not_answering_calls', 'Not Answering Calls')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('in-progress', 'In Progress'), ('closed', 'Closed'), ('untouched', 'Untouched'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU Signed'), ('converted_agreement_signed', 'Converted – Agreement Signed'), ('join_later', 'Join Later'), ('not_answering_calls', 'Not Answering Calls')], default='new', max_length=30),
        ),
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('called', 'Called'), ('follow_up', 'Follow Up'), ('interested', 'Interested'), ('meeting_scheduled', 'Meeting Scheduled'), ('dropped', 'Dropped'), ('not_interested', 'Not Interested'), ('converted', 'Converted'), ('in-progress', 'In Progress'), ('closed', 'Closed'), ('untouched', 'Untouched'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU Signed'), ('converted_agreement_signed', 'Converted – Agreement Signed'), ('join_later', 'Join Later'), ('not_answering_calls', 'Not Answering Calls')], default='new', max_length=30),
        ),
    ]
