# Generated by Django 6.0 on 2026-07-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0015_alter_crmlead_status_alter_enquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedleadnote',
            name='status',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
