# Generated by Django 6.0 on 2026-07-13 09:15

from django.db import migrations, models


def migrate_statuses(apps, schema_editor):
    Enquiry = apps.get_model('enquiries', 'Enquiry')
    FranchiseEnquiry = apps.get_model('enquiries', 'FranchiseEnquiry')
    CrmLead = apps.get_model('enquiries', 'CrmLead')

    mapping = {
        'new': 'untouched',
        'untouched': 'untouched',
        
        'called': 'not_answering',
        'contacted': 'not_answering',
        'not_answering_calls': 'not_answering',
        
        'follow_up': 'follow_up',
        'hot': 'follow_up',
        'warm': 'follow_up',
        'cold': 'follow_up',
        'in-progress': 'follow_up',
        
        'meeting_scheduled': 'visited_school',
        
        'converted': 'converted_admission',
        'converted_mou_signed': 'converted_admission',
        'converted_agreement_signed': 'converted_admission',
        
        'dropped': 'not_interested',
        'not_interested': 'not_interested',
        'join_later': 'not_interested',
        'closed': 'not_interested',
    }

    for model in [Enquiry, FranchiseEnquiry, CrmLead]:
        for old_val, new_val in mapping.items():
            model.objects.filter(status=old_val).update(status=new_val)


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0016_unifiedleadnote_status'),
    ]

    operations = [
        migrations.RunPython(migrate_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('not_answering', 'Not answering'), ('follow_up', 'Follow-up'), ('visited_school', 'Visited the school'), ('converted_admission', 'Converted to Admission'), ('joined_competition', 'Joined competition'), ('not_interested', 'Not Interested'), ('wrong_enquiry', 'Wrong enquiry')], default='untouched', max_length=30),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('not_answering', 'Not answering'), ('follow_up', 'Follow-up'), ('visited_school', 'Visited the school'), ('converted_admission', 'Converted to Admission'), ('joined_competition', 'Joined competition'), ('not_interested', 'Not Interested'), ('wrong_enquiry', 'Wrong enquiry')], default='untouched', max_length=30),
        ),
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('not_answering', 'Not answering'), ('follow_up', 'Follow-up'), ('visited_school', 'Visited the school'), ('converted_admission', 'Converted to Admission'), ('joined_competition', 'Joined competition'), ('not_interested', 'Not Interested'), ('wrong_enquiry', 'Wrong enquiry')], default='untouched', max_length=30),
        ),
    ]
