# Generated by Django 6.0 on 2026-07-13 09:23

from django.db import migrations


def migrate_interested_status(apps, schema_editor):
    Enquiry = apps.get_model('enquiries', 'Enquiry')
    FranchiseEnquiry = apps.get_model('enquiries', 'FranchiseEnquiry')
    CrmLead = apps.get_model('enquiries', 'CrmLead')

    for model in [Enquiry, FranchiseEnquiry, CrmLead]:
        model.objects.filter(status='interested').update(status='follow_up')


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0017_alter_crmlead_status_alter_enquiry_status_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_interested_status, reverse_code=migrations.RunPython.noop),
    ]
