# Generated by Django 6.0 on 2026-07-13 09:35

from django.db import migrations, models


def migrate_franchise_statuses(apps, schema_editor):
    FranchiseEnquiry = apps.get_model('enquiries', 'FranchiseEnquiry')
    CrmLead = apps.get_model('enquiries', 'CrmLead')

    mapping = {
        'not_answering': 'not_answering_calls',
        'visited_school': 'follow_up',
        'converted_admission': 'converted_agreement_signed',
        'joined_competition': 'follow_up',
        'wrong_enquiry': 'not_interested',
    }

    for old_val, new_val in mapping.items():
        FranchiseEnquiry.objects.filter(status=old_val).update(status=new_val)
        CrmLead.objects.filter(source='franchise', status=old_val).update(status=new_val)


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0018_migrate_interested_status'),
    ]

    operations = [
        migrations.RunPython(migrate_franchise_statuses, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('follow_up', 'Follow-up'), ('not_interested', 'Not Interested'), ('not_answering', 'Not answering'), ('visited_school', 'Visited the school'), ('converted_admission', 'Converted to Admission'), ('joined_competition', 'Joined competition'), ('wrong_enquiry', 'Wrong enquiry'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU Signed'), ('converted_agreement_signed', 'Converted – Agreement Signed'), ('join_later', 'Join Later'), ('not_answering_calls', 'Not Answering Calls')], default='untouched', max_length=30),
        ),
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('hot', 'Hot'), ('warm', 'Warm'), ('follow_up', 'Follow-up'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU Signed'), ('converted_agreement_signed', 'Converted – Agreement Signed'), ('join_later', 'Join Later'), ('not_interested', 'Not Interested'), ('not_answering_calls', 'Not Answering Calls')], default='untouched', max_length=30),
        ),
    ]
