# Generated by Django 6.0.3 on 2026-07-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0024_crmlead_utm_content_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaLeadSuppress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('form_id', models.CharField(blank=True, default='', max_length=64)),
                ('form_name', models.CharField(blank=True, default='', max_length=255)),
                ('crm_lead_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meta_lead_suppress',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('fb', 'Facebook'), ('insta', 'Instagram'), ('july_lp', 'Google'), ('july_meta', 'META'), ('lp_wb', 'Google')], default='web', max_length=20),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('follow_up', 'Follow-up'), ('not_interested', 'Not Interested'), ('not_answering', 'Not answering'), ('visited_school', 'Visited the school'), ('converted_admission', 'Converted to Admission'), ('joined_competition', 'Joined competition'), ('wrong_enquiry', 'Wrong enquiry'), ('interested', 'Interested'), ('hot', 'Hot'), ('warm', 'Warm'), ('cold', 'Cold'), ('converted_mou_signed', 'Converted – MOU'), ('converted_agreement_signed', 'Converted – Agreement'), ('join_later', 'Join Later'), ('not_answering_calls', 'Not Answering Calls')], default='untouched', max_length=30),
        ),
        migrations.AlterField(
            model_name='franchiseenquiry',
            name='status',
            field=models.CharField(choices=[('untouched', 'Untouched'), ('not_answering_calls', 'Not Answering Calls'), ('interested', 'Interested'), ('follow_up', 'Follow-up'), ('join_later', 'Join Later'), ('cold', 'Cold'), ('warm', 'Warm'), ('hot', 'Hot'), ('converted_mou_signed', 'Converted – MOU'), ('converted_agreement_signed', 'Converted – Agreement'), ('not_interested', 'Not Interested'), ('wrong_enquiry', 'Wrong enquiry')], default='untouched', max_length=30),
        ),
    ]
