# Generated by Django 6.0 on 2026-08-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0027_kidsenquiry_assigned_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmlead',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='crmlead',
            name='meeting_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='meeting_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchiseenquiry',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='franchiseenquiry',
            name='meeting_fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kidsenquiry',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kidsenquiry',
            name='meeting_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
