# Generated by Django 6.0 on 2026-10-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0030_crmlead_gclid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crmlead',
            name='source',
            field=models.CharField(choices=[('web', 'Website'), ('fb', 'Facebook'), ('insta', 'Instagram'), ('july_lp', 'Google'), ('july_meta', 'META'), ('lp_wb', 'Google'), ('franchise_referral', 'Referral-Franchise'), ('franchise_friends_family', 'Referral - Friends & Family'), ('referral_parents', 'Referral - Parents'), ('referral_family_friends', 'Referral - Family & Friends'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='web', max_length=40),
        ),
    ]
