# Generated by Django 5.0.14 on 2026-01-30 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('franchises', '0008_franchisegalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUDIO_RHYMES', 'Audio Rhymes'), ('VIDEOS', 'Watch • Hear • Learn'), ('NEWSLETTERS', 'Newsletters'), ('STUDENTS_KIT', 'Students Kit'), ('PARENTING_TIPS', 'Parenting Tips & Articles')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload document, audio, or video file', upload_to='parent_documents/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='parent_documents/thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, help_text='Leave blank for global documents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_documents', to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Parent Document',
                'verbose_name_plural': 'Parent Documents',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
