# Generated by Django 5.0.14 on 2026-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentdocument',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g., AY 2025-26 (Required for Holiday Lists)', max_length=20),
        ),
        migrations.AddField(
            model_name='parentdocument',
            name='state',
            field=models.CharField(blank=True, choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UK', 'Uttarakhand'), ('WB', 'West Bengal')], help_text='Required for Holiday Lists', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='parentdocument',
            name='category',
            field=models.CharField(choices=[('AUDIO_RHYMES', 'Audio Rhymes'), ('VIDEOS', 'Watch • Hear • Learn'), ('NEWSLETTERS', 'Newsletters'), ('STUDENTS_KIT', 'Students Kit'), ('PARENTING_TIPS', 'Parenting Tips & Articles'), ('HOLIDAY_LISTS', 'Holiday Lists')], max_length=50),
        ),
    ]
