# Generated by Django 6.0 on 2026-03-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_parentdocument_academic_year_parentdocument_state_and_more'),
        ('franchises', '0008_franchisegalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SOP', 'Standard Operating Procedures (SOP)'), ('INFRASTRUCTURE_MANUAL', 'Infrastructure Manual & Purchase List'), ('FORMATS', 'Formats'), ('LEASE_AGREEMENT_DOCUMENTS', 'Lease Agreement Documents'), ('INDENT_DOCUMENTS', 'Indent Documents (Inside & Outside AP)'), ('ORDERING_DOCUMENTS', 'Ordering Documents (IK & SM)'), ('STUDENT_TRANSFER_POLICY', 'Student Transfer Policy'), ('ACADEMIC_DOCUMENTS', 'Academic Documents'), ('REFRESHER_COURSE', 'Refresher Course'), ('AKSHARABHYASAM_SUPPORT_SHEETS', 'Aksharabhyasam Support Sheets'), ('STUDENTS_KIT', 'Students Kit'), ('FRANCHISE_REFERRAL_INCENTIVES', 'Franchise Referral Incentives'), ('ROYALTY_PAYMENTS', 'Royalty Payments')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='Upload document file (PDF/DOC/etc).', upload_to='franchise_documents/')),
                ('academic_year', models.CharField(blank=True, help_text='Optional academic year, if applicable.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(blank=True, help_text='Leave blank for global documents', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='franchise_documents', to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Franchise Resource Document',
                'verbose_name_plural': 'Franchise Resource Documents',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
