# Generated by Django 6.0 on 2026-03-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_franchisedocument'),
        ('franchises', '0008_franchisegalleryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('INSIDE_AP', 'Inside AP'), ('OUTSIDE_AP', 'Outside AP')], max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indent_requests', to='franchises.franchise')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
