# Generated by Django 6.0.3 on 2026-03-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_indentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdocument',
            name='category',
            field=models.CharField(choices=[('AUDIO_RHYMES', 'Audio Rhymes'), ('VIDEOS', 'Watch • Hear • Learn'), ('NEWSLETTERS', 'Newsletters'), ('STUDENTS_KIT', 'Students Kit'), ('PARENTING_TIPS', 'Parenting Tips & Articles'), ('HOLIDAY_LISTS', 'Holiday Lists'), ('PRESCHOOL_POLICIES', 'Preschool Policies (PDF)'), ('CLASS_TIMETABLE', 'Class Timetable (PDF)')], max_length=50),
        ),
    ]
