# Generated by Django 6.0 on 2026-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_parentdocument_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchisedocument',
            name='source_path',
            field=models.CharField(blank=True, help_text='Legacy relative path under pc/ (e.g. holidayslist-2026-27/AP Holiday List.pdf) for Centre Page links.', max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='franchisedocument',
            name='category',
            field=models.CharField(choices=[('SOP', 'Standard Operating Procedures (SOP)'), ('INFRASTRUCTURE_MANUAL', 'Infrastructure Manual & Purchase List'), ('FORMATS', 'Formats'), ('LEASE_AGREEMENT_DOCUMENTS', 'Lease Agreement Documents'), ('INDENT_DOCUMENTS', 'Indent Documents (Inside & Outside AP)'), ('ORDERING_DOCUMENTS', 'Ordering Documents (IK & SM)'), ('STUDENT_TRANSFER_POLICY', 'Student Transfer Policy'), ('ACADEMIC_DOCUMENTS', 'Academic Documents'), ('REFRESHER_COURSE', 'Refresher Course'), ('AKSHARABHYASAM_SUPPORT_SHEETS', 'Aksharabhyasam Support Sheets'), ('STUDENTS_KIT', 'Students Kit'), ('FRANCHISE_REFERRAL_INCENTIVES', 'Franchise Referral Incentives'), ('ROYALTY_PAYMENTS', 'Royalty Payments'), ('SOCIAL_MEDIA_SUPPORT', 'Social Media Uploads & Support Files'), ('WELCOME_LETTERS', 'Welcome Letters'), ('SUMMER_CAMP', 'Summer Camp'), ('HOLIDAY_LISTS', 'Holiday Lists'), ('WATCH_HEAR_LEARN', 'Watch • Hear • Learn'), ('ADMISSION_COUNSELLING', 'Admission Counselling'), ('ARTWORKS_MARKETING', 'Artworks & Marketing'), ('CONCEPT_ROOM_DISPLAYS', 'Concept Room Pictures & Displays'), ('REPORT_CARD_COMMENTS', 'Report Card Comments'), ('PARENT_ORIENTATION', 'Parents Orientation'), ('COUNSELLING_TOOLS', 'Counselling Tools & Report Cards'), ('PARENTING_TIPS', 'Parenting Tips & Articles')], max_length=50),
        ),
    ]
