from django.urls import path

from .portal_views import (
    AdminAnnouncementCampaignDetailView,
    AdminAnnouncementCampaignListCreateView,
    AdminSupportTicketListView,
    admin_remind_support_ticket_centre,
    FranchiseAnnouncementDetailView,
    FranchiseNotificationReadView,
    FranchiseNotificationsView,
    cron_dispatch_scheduled_announcements,
    FranchiseAnnouncementListCreateView,
    FranchiseAttendanceBulkUpsertView,
    FranchiseAttendanceClearDateView,
    FranchiseAttendanceClosedDayDetailView,
    FranchiseAttendanceClosedDayListCreateView,
    FranchiseAttendanceHolidaysView,
    FranchiseAttendanceDetailView,
    FranchiseAttendanceListCreateView,
    FranchiseFeeDetailView,
    FranchiseFeeLineStatusView,
    FranchiseFeeListCreateView,
    FranchiseFeeSummaryView,
    FranchiseHomeworkDetailView,
    FranchiseHomeworkListCreateView,
    FranchiseDailyActivityListCreateView,
    FranchiseDailyActivityDetailView,
    FranchiseSupportTicketDetailView,
    FranchiseSupportTicketListView,
    FranchiseTransportAssignmentDetailView,
    FranchiseTransportAssignmentListCreateView,
    FranchiseTransportDetailView,
    FranchiseTransportListCreateView,
    ParentAnnouncementListView,
    ParentAttendanceListView,
    ParentCalendarAttendanceView,
    ParentFeeListView,
    ParentFeePaymentConfigView,
    ParentFeePayConfirmView,
    ParentFeePaymentReceiptView,
    ParentFeePayInitView,
    ParentFeeSummaryView,
    ParentHomeworkListView,
    ParentHomeworkSubmitView,
    ParentDailyActivityListView,
    ParentGradeListView,
    ParentNotificationReadView,
    ParentSupportTicketListCreateView,
    ParentLiveTransportView,
    ParentTransportListView,
    ParentNotificationsView,

    FranchiseDriverListCreateView,
    FranchiseDriverDetailView,
    auth_driver_trip_detail,
    auth_driver_start_trip,
    auth_driver_post_location,
    auth_driver_update_student_status,
    auth_driver_complete_trip,
    auth_driver_toggle_gps,
)
from .views import (
    AdminAchievementDetailView,
    AdminAchievementListCreateView,
    AdminStudentMiniListView,
    FranchiseAchievementListView,
    FranchiseGradeDetailView,
    FranchiseGradeListCreateView,
    FranchiseStudentDetailView,
    FranchiseStudentListCreateView,
    FranchiseStudentMiniListView,
    ParentAchievementListView,
    ParentDashboardView,
    ParentStudentDetailView,
    ParentStudentGradesView,
    ParentStudentListView,
)

urlpatterns = [
    path("parent/dashboard/", ParentDashboardView.as_view(), name="parent-dashboard"),
    path("parent/students/", ParentStudentListView.as_view(), name="parent-students"),
    path("parent/students/<int:pk>/", ParentStudentDetailView.as_view(), name="parent-student-detail"),
    path("parent/students/<int:student_id>/grades/", ParentStudentGradesView.as_view(), name="parent-student-grades"),
    path("parent/achievements/", ParentAchievementListView.as_view(), name="parent-achievements"),
    path("parent/homework/", ParentHomeworkListView.as_view(), name="parent-homework"),
    path("parent/homework/<int:pk>/submit/", ParentHomeworkSubmitView.as_view(), name="parent-homework-submit"),
    path("parent/daily-activities/", ParentDailyActivityListView.as_view(), name="parent-daily-activities"),
    path("parent/grades/", ParentGradeListView.as_view(), name="parent-grades-all"),
    path("parent/announcements/", ParentAnnouncementListView.as_view(), name="parent-announcements"),
    path("parent/attendance/", ParentAttendanceListView.as_view(), name="parent-attendance"),
    path("parent/calendar-attendance/", ParentCalendarAttendanceView.as_view(), name="parent-calendar-attendance"),
    path("parent/fees/", ParentFeeListView.as_view(), name="parent-fees"),
    path("parent/fees/summary/", ParentFeeSummaryView.as_view(), name="parent-fees-summary"),
    path("parent/fees/payment/config/", ParentFeePaymentConfigView.as_view(), name="parent-fees-payment-config"),
    path("parent/fees/payment/init/", ParentFeePayInitView.as_view(), name="parent-fees-payment-init"),
    path("parent/fees/payment/confirm/", ParentFeePayConfirmView.as_view(), name="parent-fees-payment-confirm"),
    path("parent/fees/payment/receipt/", ParentFeePaymentReceiptView.as_view(), name="parent-fees-payment-receipt"),
    path("parent/transport/", ParentTransportListView.as_view(), name="parent-transport"),
    path("parent/transport/live/", ParentLiveTransportView.as_view(), name="parent-transport-live"),
    path("parent/notifications/", ParentNotificationsView.as_view(), name="parent-notifications"),
    path("parent/notifications/read/", ParentNotificationReadView.as_view(), name="parent-notification-read"),
    path("parent/tickets/", ParentSupportTicketListCreateView.as_view(), name="parent-tickets"),
    path("franchise/students/", FranchiseStudentListCreateView.as_view(), name="franchise-students"),
    path("franchise/students/mini/", FranchiseStudentMiniListView.as_view(), name="franchise-students-mini"),
    path("franchise/students/<int:pk>/", FranchiseStudentDetailView.as_view(), name="franchise-student-detail"),
    path("franchise/students-mini/", FranchiseStudentMiniListView.as_view(), name="franchise-students-mini-alt"),
    path("franchise/grades/", FranchiseGradeListCreateView.as_view(), name="franchise-grades"),
    path("franchise/grades/<int:pk>/", FranchiseGradeDetailView.as_view(), name="franchise-grade-detail"),
    path("admin/achievements/", AdminAchievementListCreateView.as_view(), name="admin-achievements"),
    path("admin/achievements/<int:pk>/", AdminAchievementDetailView.as_view(), name="admin-achievement-detail"),
    path("admin/students/mini/", AdminStudentMiniListView.as_view(), name="admin-students-mini"),
    path("admin/announcements/", AdminAnnouncementCampaignListCreateView.as_view(), name="admin-announcements"),
    path("admin/announcements/<int:pk>/", AdminAnnouncementCampaignDetailView.as_view(), name="admin-announcement-detail"),
    path("admin/tickets/", AdminSupportTicketListView.as_view(), name="admin-tickets"),
    path("admin/tickets/<int:pk>/remind-centre/", admin_remind_support_ticket_centre, name="admin-ticket-remind-centre"),
    path("franchise/achievements/", FranchiseAchievementListView.as_view(), name="franchise-achievements"),
    path("franchise/homework/", FranchiseHomeworkListCreateView.as_view(), name="franchise-homework"),
    path("franchise/homework/<int:pk>/", FranchiseHomeworkDetailView.as_view(), name="franchise-homework-detail"),
    path("franchise/daily-activities/", FranchiseDailyActivityListCreateView.as_view(), name="franchise-daily-activities"),
    path("franchise/daily-activities/<int:pk>/", FranchiseDailyActivityDetailView.as_view(), name="franchise-daily-activity-detail"),
    path("franchise/announcements/", FranchiseAnnouncementListCreateView.as_view(), name="franchise-announcements"),
    path("franchise/announcements/<int:pk>/", FranchiseAnnouncementDetailView.as_view(), name="franchise-announcement-detail"),
    path("franchise/notifications/", FranchiseNotificationsView.as_view(), name="franchise-notifications"),
    path("franchise/notifications/read/", FranchiseNotificationReadView.as_view(), name="franchise-notification-read"),
    path("cron/dispatch-announcements/", cron_dispatch_scheduled_announcements, name="cron-dispatch-announcements"),
    path("franchise/attendance/", FranchiseAttendanceListCreateView.as_view(), name="franchise-attendance"),
    path("franchise/attendance/bulk/", FranchiseAttendanceBulkUpsertView.as_view(), name="franchise-attendance-bulk"),
    path("franchise/attendance/clear/", FranchiseAttendanceClearDateView.as_view(), name="franchise-attendance-clear"),
    path("franchise/attendance/holidays/", FranchiseAttendanceHolidaysView.as_view(), name="franchise-attendance-holidays"),
    path("franchise/attendance/closed-days/", FranchiseAttendanceClosedDayListCreateView.as_view(), name="franchise-attendance-closed-days"),
    path("franchise/attendance/closed-days/<int:pk>/", FranchiseAttendanceClosedDayDetailView.as_view(), name="franchise-attendance-closed-day-detail"),
    path("franchise/attendance/<int:pk>/", FranchiseAttendanceDetailView.as_view(), name="franchise-attendance-detail"),
    path("franchise/fees/", FranchiseFeeListCreateView.as_view(), name="franchise-fees"),
    path("franchise/fees/summary/", FranchiseFeeSummaryView.as_view(), name="franchise-fees-summary"),
    path("franchise/fees/line-status/", FranchiseFeeLineStatusView.as_view(), name="franchise-fee-line-status"),
    path("franchise/fees/<int:pk>/", FranchiseFeeDetailView.as_view(), name="franchise-fee-detail"),
    path("franchise/transport/", FranchiseTransportListCreateView.as_view(), name="franchise-transport"),
    path("franchise/transport/<int:pk>/", FranchiseTransportDetailView.as_view(), name="franchise-transport-detail"),
    path("franchise/transport-assignments/", FranchiseTransportAssignmentListCreateView.as_view(), name="franchise-transport-assignments"),
    path("franchise/transport-assignments/<int:pk>/", FranchiseTransportAssignmentDetailView.as_view(), name="franchise-transport-assignment-detail"),
    path("franchise/tickets/", FranchiseSupportTicketListView.as_view(), name="franchise-tickets"),
    path("franchise/tickets/<int:pk>/", FranchiseSupportTicketDetailView.as_view(), name="franchise-ticket-detail"),

    # Authenticated Driver URLs
    path("driver/me/trip/", auth_driver_trip_detail, name="auth-driver-trip-detail"),
    path("driver/me/trip/start/", auth_driver_start_trip, name="auth-driver-start-trip"),
    path("driver/me/trip/location/", auth_driver_post_location, name="auth-driver-post-location"),
    path("driver/me/trip/student-status/", auth_driver_update_student_status, name="auth-driver-update-status"),
    path("driver/me/trip/complete/", auth_driver_complete_trip, name="auth-driver-complete-trip"),
    path("driver/me/trip/toggle-gps/", auth_driver_toggle_gps, name="auth-driver-toggle-gps"),

    # Franchise-side Driver Management
    path("franchise/drivers/", FranchiseDriverListCreateView.as_view(), name="franchise-drivers"),
    path("franchise/drivers/<int:pk>/", FranchiseDriverDetailView.as_view(), name="franchise-driver-detail"),
]

