from django.urls import path

from .portal_views import (
    FranchiseAnnouncementDetailView,
    FranchiseAnnouncementListCreateView,
    FranchiseAttendanceDetailView,
    FranchiseAttendanceListCreateView,
    FranchiseFeeDetailView,
    FranchiseFeeListCreateView,
    FranchiseHomeworkDetailView,
    FranchiseHomeworkListCreateView,
    FranchiseSupportTicketDetailView,
    FranchiseSupportTicketListView,
    FranchiseTransportDetailView,
    FranchiseTransportListCreateView,
    ParentAnnouncementListView,
    ParentAttendanceListView,
    ParentCalendarAttendanceView,
    ParentFeeListView,
    ParentHomeworkListView,
    ParentGradeListView,
    ParentNotificationReadView,
    ParentSupportTicketListCreateView,
    ParentTransportListView,
    ParentNotificationsView,
)
from .views import (
    FranchiseAchievementDetailView,
    FranchiseAchievementListCreateView,
    FranchiseGradeDetailView,
    FranchiseGradeListCreateView,
    FranchiseStudentDetailView,
    FranchiseStudentListCreateView,
    FranchiseStudentMiniListView,
    ParentAchievementListView,
    ParentDashboardView,
    ParentStudentDetailView,
    ParentStudentGradesView,
    ParentStudentListView,
)

urlpatterns = [
    path("parent/dashboard/", ParentDashboardView.as_view(), name="parent-dashboard"),
    path("parent/students/", ParentStudentListView.as_view(), name="parent-students"),
    path("parent/students/<int:pk>/", ParentStudentDetailView.as_view(), name="parent-student-detail"),
    path("parent/students/<int:student_id>/grades/", ParentStudentGradesView.as_view(), name="parent-student-grades"),
    path("parent/achievements/", ParentAchievementListView.as_view(), name="parent-achievements"),
    path("parent/homework/", ParentHomeworkListView.as_view(), name="parent-homework"),
    path("parent/grades/", ParentGradeListView.as_view(), name="parent-grades-all"),
    path("parent/announcements/", ParentAnnouncementListView.as_view(), name="parent-announcements"),
    path("parent/attendance/", ParentAttendanceListView.as_view(), name="parent-attendance"),
    path("parent/calendar-attendance/", ParentCalendarAttendanceView.as_view(), name="parent-calendar-attendance"),
    path("parent/fees/", ParentFeeListView.as_view(), name="parent-fees"),
    path("parent/transport/", ParentTransportListView.as_view(), name="parent-transport"),
    path("parent/notifications/", ParentNotificationsView.as_view(), name="parent-notifications"),
    path("parent/notifications/read/", ParentNotificationReadView.as_view(), name="parent-notification-read"),
    path("parent/tickets/", ParentSupportTicketListCreateView.as_view(), name="parent-tickets"),
    path("franchise/students/", FranchiseStudentListCreateView.as_view(), name="franchise-students"),
    path("franchise/students/mini/", FranchiseStudentMiniListView.as_view(), name="franchise-students-mini"),
    path("franchise/students/<int:pk>/", FranchiseStudentDetailView.as_view(), name="franchise-student-detail"),
    path("franchise/students-mini/", FranchiseStudentMiniListView.as_view(), name="franchise-students-mini-alt"),
    path("franchise/grades/", FranchiseGradeListCreateView.as_view(), name="franchise-grades"),
    path("franchise/grades/<int:pk>/", FranchiseGradeDetailView.as_view(), name="franchise-grade-detail"),
    path("franchise/achievements/", FranchiseAchievementListCreateView.as_view(), name="franchise-achievements"),
    path("franchise/achievements/<int:pk>/", FranchiseAchievementDetailView.as_view(), name="franchise-achievement-detail"),
    path("franchise/homework/", FranchiseHomeworkListCreateView.as_view(), name="franchise-homework"),
    path("franchise/homework/<int:pk>/", FranchiseHomeworkDetailView.as_view(), name="franchise-homework-detail"),
    path("franchise/announcements/", FranchiseAnnouncementListCreateView.as_view(), name="franchise-announcements"),
    path("franchise/announcements/<int:pk>/", FranchiseAnnouncementDetailView.as_view(), name="franchise-announcement-detail"),
    path("franchise/attendance/", FranchiseAttendanceListCreateView.as_view(), name="franchise-attendance"),
    path("franchise/attendance/<int:pk>/", FranchiseAttendanceDetailView.as_view(), name="franchise-attendance-detail"),
    path("franchise/fees/", FranchiseFeeListCreateView.as_view(), name="franchise-fees"),
    path("franchise/fees/<int:pk>/", FranchiseFeeDetailView.as_view(), name="franchise-fee-detail"),
    path("franchise/transport/", FranchiseTransportListCreateView.as_view(), name="franchise-transport"),
    path("franchise/transport/<int:pk>/", FranchiseTransportDetailView.as_view(), name="franchise-transport-detail"),
    path("franchise/tickets/", FranchiseSupportTicketListView.as_view(), name="franchise-tickets"),
    path("franchise/tickets/<int:pk>/", FranchiseSupportTicketDetailView.as_view(), name="franchise-ticket-detail"),
]

