# Generated by Django 6.0.1 on 2026-02-17 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0008_franchisegalleryitem'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='franchises.franchise'),
        ),
        migrations.AddField(
            model_name='update',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
