# Generated by Django 6.0.1 on 2026-02-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_update_franchise_update_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='date',
        ),
        migrations.AddField(
            model_name='update',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
