from django.urls import path

from .views import (
    AdminAllEnquiryListView,
    AdminCrmCentresView,
    AdminCrmCitiesView,
    AdminCrmLeadDetailView,
    AdminCrmLeadListView,
    AdminCrmLeadNoteCreateView,
    AdminCrmLeadRemindersView,
    AdminCrmReportsView,
    AdminCrmLeadStatsView,
    AdminCrmSendReminderView,
    AdminCrmStatesView,
    AdminEnquiryListView,
    CrmLeadCreateView,
    CrmLeadMeetingPreferenceView,
    EnquiryCreateView,
    EnquiryUpdateView,
    FranchiseEnquiryCreateView,
    FranchiseEnquiryListView,
    FranchiseEnquiryUpdateView,
    FranchiseLeadAdminUpdateView,
    FranchiseLeadPartnerUpdateView,
    LandingEnquirySubmitView,
    LandingKidsEnquiryListView,
    LeadNoteListCreateView,
    SendOTPView,
    VerifyOTPView,
)

urlpatterns = [
    path("crm-leads/", CrmLeadCreateView.as_view(), name="crm-lead-create"),
    path("crm-leads/meeting-preference/", CrmLeadMeetingPreferenceView.as_view(), name="crm-lead-meeting-preference"),
    path("admin/crm-leads/", AdminCrmLeadListView.as_view(), name="admin-crm-leads"),
    path("admin/crm-leads/reports/", AdminCrmReportsView.as_view(), name="admin-crm-leads-reports"),
    path("admin/crm-leads/stats/", AdminCrmLeadStatsView.as_view(), name="admin-crm-leads-stats"),
    path("admin/crm-leads/reminders/", AdminCrmLeadRemindersView.as_view(), name="admin-crm-leads-reminders"),
    path("admin/crm-leads/send-reminder/", AdminCrmSendReminderView.as_view(), name="admin-crm-send-reminder"),
    path("admin/crm-centres/", AdminCrmCentresView.as_view(), name="admin-crm-centres"),
    path("admin/crm-cities/", AdminCrmCitiesView.as_view(), name="admin-crm-cities"),
    path("admin/crm-states/", AdminCrmStatesView.as_view(), name="admin-crm-states"),
    path("admin/crm-leads/<str:pk>/", AdminCrmLeadDetailView.as_view(), name="admin-crm-lead-detail"),
    path("admin/crm-leads/<str:pk>/notes/", AdminCrmLeadNoteCreateView.as_view(), name="admin-crm-lead-note"),
    path("landing-submit/", LandingEnquirySubmitView.as_view(), name="landing-enquiry-submit"),
    path("landing-leads/", LandingKidsEnquiryListView.as_view(), name="landing-kids-enquiry-list"),
    path("send-otp/", SendOTPView.as_view(), name="send-otp"),
    path("verify-otp/", VerifyOTPView.as_view(), name="verify-otp"),
    path("submit/", EnquiryCreateView.as_view(), name="enquiry-create"),
    path("franchise-submit/", FranchiseEnquiryCreateView.as_view(), name="franchise-enquiry-create"),
    path("admin/", AdminEnquiryListView.as_view(), name="enquiry-admin-list"),
    path("admin/all/", AdminAllEnquiryListView.as_view(), name="enquiry-admin-all-list"),
    path("admin/<int:pk>/", EnquiryUpdateView.as_view(), name="enquiry-update"),
    path("admin/franchise/<int:pk>/", FranchiseLeadAdminUpdateView.as_view(), name="franchise-lead-admin-update"),
    path("franchise/", FranchiseEnquiryListView.as_view(), name="enquiry-franchise-list"),
    path("franchise/lead/<int:pk>/", FranchiseLeadPartnerUpdateView.as_view(), name="franchise-lead-partner-update"),
    path("franchise/<int:pk>/", FranchiseEnquiryUpdateView.as_view(), name="enquiry-franchise-update"),
    path("notes/<str:lead_id>/", LeadNoteListCreateView.as_view(), name="lead-notes"),
]
