from django.urls import path

from .views import (
    AdminAllEnquiryListView,
    AdminCrmCampaignsView,
    AdminCrmMediumsView,
    AdminCrmCentresView,
    AdminCrmCitiesView,
    AdminCrmLeadAddView,
    AdminCrmLeadDetailView,
    AdminCrmLeadListView,
    AdminCrmLeadNoteCreateView,
    AdminCrmLeadRemindersView,
    AdminCrmReportsView,
    AdminCrmStateLeadReportView,
    AdminCrmLeadStatsView,
    AdminCrmSendReminderView,
    AdminCrmStatesView,
    AdminCrmTeamCitiesView,
    AdminCrmTeamStatusView,
    AdminCrmTeamTransferView,
    AdminCrmTeamUserLeadsView,
    AdminCrmTeamUserView,
    AdminCrmTeamView,
    AdminCrmUsersView,
    AdminEnquiryListView,
    CrmLeadCreateView,
    CrmLeadMeetingPreferenceView,
    MetaLeadWebhookView,
    MetaLeadSyncView,
    EnquiryCreateView,
    EnquiryUpdateView,
    FranchiseEnquiryCreateView,
    FranchiseEnquiryListView,
    FranchiseEnquiryUpdateView,
    FranchiseLeadAdminUpdateView,
    FranchiseLeadPartnerUpdateView,
    LandingEnquirySubmitView,
    LandingKidsEnquiryListView,
    LeadNoteListCreateView,
    SendOTPView,
    VerifyOTPView,
)

urlpatterns = [
    path("crm-leads/", CrmLeadCreateView.as_view(), name="crm-lead-create"),
    path("crm-leads/meeting-preference/", CrmLeadMeetingPreferenceView.as_view(), name="crm-lead-meeting-preference"),
    path("meta-leads/webhook/", MetaLeadWebhookView.as_view(), name="meta-lead-webhook"),
    path("meta-leads/webhook", MetaLeadWebhookView.as_view()),
    path("meta-leads/sync/", MetaLeadSyncView.as_view(), name="meta-lead-sync"),
    path("meta-leads/sync", MetaLeadSyncView.as_view()),

    path("admin/crm-leads/", AdminCrmLeadListView.as_view(), name="admin-crm-leads"),
    path("admin/crm-leads/reports/", AdminCrmReportsView.as_view(), name="admin-crm-leads-reports"),
    path("admin/crm-leads/reports/state-summary/", AdminCrmStateLeadReportView.as_view(), name="admin-crm-state-lead-report"),
    path("admin/crm-leads/stats/", AdminCrmLeadStatsView.as_view(), name="admin-crm-leads-stats"),

    path("admin/crm-leads/reminders/", AdminCrmLeadRemindersView.as_view(), name="admin-crm-leads-reminders"),
    path("admin/crm-leads/send-reminder/", AdminCrmSendReminderView.as_view(), name="admin-crm-send-reminder"),
    path("admin/crm-centres/", AdminCrmCentresView.as_view(), name="admin-crm-centres"),
    path("admin/crm-campaigns/", AdminCrmCampaignsView.as_view(), name="admin-crm-campaigns"),
    path("admin/crm-mediums/", AdminCrmMediumsView.as_view(), name="admin-crm-mediums"),
    path("admin/crm-cities/", AdminCrmCitiesView.as_view(), name="admin-crm-cities"),
    path("admin/crm-states/", AdminCrmStatesView.as_view(), name="admin-crm-states"),
    path("admin/crm-users/", AdminCrmUsersView.as_view(), name="admin-crm-users"),
    path("admin/crm-leads/add/", AdminCrmLeadAddView.as_view(), name="admin-crm-lead-add"),
    path("admin/crm-team/", AdminCrmTeamView.as_view(), name="admin-crm-team"),
    path("admin/crm-team/cities/", AdminCrmTeamCitiesView.as_view(), name="admin-crm-team-cities"),
    path("admin/crm-team/<int:user_id>/", AdminCrmTeamUserView.as_view(), name="admin-crm-team-user"),
    path("admin/crm-team/<int:user_id>/leads/", AdminCrmTeamUserLeadsView.as_view(), name="admin-crm-team-leads"),
    path("admin/crm-team/<int:user_id>/transfer/", AdminCrmTeamTransferView.as_view(), name="admin-crm-team-transfer"),
    path("admin/crm-team/<int:user_id>/status/", AdminCrmTeamStatusView.as_view(), name="admin-crm-team-status"),
    path("admin/crm-leads/<str:pk>/", AdminCrmLeadDetailView.as_view(), name="admin-crm-lead-detail"),
    path("admin/crm-leads/<str:pk>/notes/", AdminCrmLeadNoteCreateView.as_view(), name="admin-crm-lead-note"),
    path("landing-submit/", LandingEnquirySubmitView.as_view(), name="landing-enquiry-submit"),
    path("landing-leads/", LandingKidsEnquiryListView.as_view(), name="landing-kids-enquiry-list"),
    path("send-otp/", SendOTPView.as_view(), name="send-otp"),
    path("verify-otp/", VerifyOTPView.as_view(), name="verify-otp"),
    path("submit/", EnquiryCreateView.as_view(), name="enquiry-create"),
    path("franchise-submit/", FranchiseEnquiryCreateView.as_view(), name="franchise-enquiry-create"),
    path("admin/", AdminEnquiryListView.as_view(), name="enquiry-admin-list"),
    path("admin/all/", AdminAllEnquiryListView.as_view(), name="enquiry-admin-all-list"),
    path("admin/<int:pk>/", EnquiryUpdateView.as_view(), name="enquiry-update"),
    path("admin/franchise/<int:pk>/", FranchiseLeadAdminUpdateView.as_view(), name="franchise-lead-admin-update"),
    path("franchise/", FranchiseEnquiryListView.as_view(), name="enquiry-franchise-list"),
    path("franchise/lead/<int:pk>/", FranchiseLeadPartnerUpdateView.as_view(), name="franchise-lead-partner-update"),
    path("franchise/<int:pk>/", FranchiseEnquiryUpdateView.as_view(), name="enquiry-franchise-update"),
    path("notes/<str:lead_id>/", LeadNoteListCreateView.as_view(), name="lead-notes"),
]
