# Generated by Django 5.2.9 on 2026-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Name of the city', max_length=100, unique=True)),
                ('landmark_name', models.CharField(help_text='Name of the famous landmark', max_length=200)),
                ('landmark_type', models.CharField(help_text='Type of landmark (e.g., backwaters, fort_generic, temple_bengal, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Display this location on the website')),
                ('display_order', models.IntegerField(default=0, help_text='Order to display (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Franchise Location',
                'verbose_name_plural': 'Franchise Locations',
                'ordering': ['display_order', 'city_name'],
            },
        ),
    ]
