# Generated by Django 5.2.9 on 2026-01-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0003_franchiselocation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiselocation',
            name='landmark_name',
        ),
        migrations.RemoveField(
            model_name='franchiselocation',
            name='landmark_type',
        ),
    ]
