# Generated by Django 5.2.9 on 2026-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0004_remove_franchiselocation_landmark_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='google_map_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='franchise',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
