# Generated by Django 5.2.9 on 2026-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0005_franchise_facebook_url_franchise_google_map_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiselocation',
            name='landmark_name',
            field=models.CharField(blank=True, default='', help_text='Name of the landmark (e.g., Charminar)', max_length=150),
        ),
        migrations.AddField(
            model_name='franchiselocation',
            name='landmark_type',
            field=models.CharField(choices=[('backwaters', 'Backwaters'), ('fort_generic', 'Fort (Generic)'), ('temple_bengal', 'Temple (Bengal Style)'), ('vidhana_soudha', 'Vidhana Soudha'), ('carpet', 'Carpet/Textile'), ('marine_drive', 'Marine Drive'), ('bandel_church', 'Bandel Church'), ('howrah_bridge', 'Howrah Bridge'), ('charminar', 'Charminar'), ('arch_dam', 'Arch Dam'), ('fort_water', 'Water Fort'), ('temple_gopuram', 'Temple Gopuram'), ('lake_generic', 'Lake (Generic)'), ('beach_generic', 'Beach (Generic)'), ('bara_imambara', 'Bara Imambara'), ('hill_park', 'Hill Park'), ('gateway_of_india', 'Gateway of India'), ('rockfort', 'Rockfort'), ('golghar', 'Golghar'), ('shaniwar_wada', 'Shaniwar Wada'), ('waterfall', 'Waterfall'), ('temple_kalinga', 'Temple (Kalinga Style)'), ('temple_kerala', 'Temple (Kerala Style)'), ('temple_padmanabhaswamy', 'Padmanabhaswamy Temple'), ('cactus_garden', 'Cactus Garden'), ('beach_rk', 'RK Beach'), ('temple_hill', 'Hill Temple'), ('fort_moat', 'Fort Moat')], default='fort_generic', help_text='Type of landmark icon to display', max_length=50),
        ),
    ]
