# Generated by Django 5.2.9 on 2026-01-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0006_franchiselocation_landmark_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseHeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='franchises/hero_slides/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Franchise Hero Slide',
                'verbose_name_plural': 'Franchise Hero Slides',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
