# Generated by Django 5.2.9 on 2026-01-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0007_franchiseheroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(help_text='Photo or Video Thumbnail', upload_to='franchises/gallery/')),
                ('video_link', models.URLField(blank=True, help_text='YouTube/Vimeo link for videos')),
                ('academic_year', models.CharField(default='2023-24', help_text='e.g. 2023-24', max_length=20)),
                ('event_category', models.CharField(default='General', help_text='e.g. Annual Day', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Franchise Gallery Item',
                'verbose_name_plural': 'Franchise Gallery Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
