# Generated by Django 6.0 on 2026-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0009_parentprofile_contact_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='notifications_muted',
            field=models.BooleanField(default=False, help_text='Parent preference: mute in-app announcement highlights'),
        ),
    ]
