# Generated by Django 6.0.3 on 2026-04-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0010_portal_and_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='franchise',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
