# Generated by Django 6.0 on 2026-04-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0012_alter_parentprofile_notifications_muted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchise',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
