# Generated by Django 6.0 on 2026-05-04 11:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0013_alter_franchise_latitude_alter_franchise_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Phone number must be exactly 10 digits.')]),
        ),
    ]
