# Generated by Django 6.0 on 2026-05-11 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0015_franchise_school_program_cards'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='franchise',
            table='franchise',
        ),
        migrations.AlterModelTable(
            name='franchiselocation',
            table='franchise_location',
        ),
    ]
