# Generated by Django 6.0 on 2026-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0016_alter_franchise_table_alter_franchiselocation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
