# Generated by Django 6.0 on 2026-07-10 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchises', '0020_driverprofile_vehicle_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='franchises.driverprofile')),
            ],
        ),
    ]
